# This is a basic workflow to help you get started with Actions

name: Dispatch Update

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Generate GitHub Apps token
        uses: tibdex/github-app-token@v2
        id: create_token
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.PRIVATE_KEY }}
      - run: |
          curl -X POST -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ steps.create_token.outputs.token }}" "https://github.com/jj1guj/github-actions-practice/dispatches" -d '{ "event_type": "update" }'
